--如果过程存在，删除过程
go
IF EXISTS(SELECT * from sys.procedures
WHERE NAME ='GetStuCou') 
DROP PROCEDURE GetStuCou
GO

--创建GetStuCou过程
CREATE PROCEDURE GetStuCou
AS
SELECT TELE
FROM DORM
LEFT JOIN STUDENT ON STUDENT.DORMNO=DORM.DORMNO 
LEFT JOIN DEPARTMENT ON STUDENT.DNO=DEPARTMENT.DNO
WHERE DEPARTMENT.DNAME='计算机系'
GO 
EXEC GetStuCou
GO
SP_HELPTEXT GetStuCou
GO
SP_DEPENDS GetStuCou